export interface UserAction {
  id: string;
  type: 'withdrawal' | 'investment';
  name: string;
  location: string;
  amount: number;
  timestamp: Date;
}

const userActions: UserAction[] = [
  {
    id: "1",
    type: "withdrawal",
    name: "Enola Rutherford",
    location: "Jacobport, Italy",
    amount: 53982.56,
    timestamp: new Date(),
  },
  {
    id: "2", 
    type: "investment",
    name: "Sarah Thompson",
    location: "New York, USA",
    amount: 25000.00,
    timestamp: new Date(),
  },
  {
    id: "3",
    type: "withdrawal",
    name: "James Carter",
    location: "London, UK", 
    amount: 18750.25,
    timestamp: new Date(),
  },
  {
    id: "4",
    type: "investment",
    name: "Amina Khalid",
    location: "Dubai, UAE",
    amount: 42300.80,
    timestamp: new Date(),
  },
  {
    id: "5",
    type: "withdrawal",
    name: "Lucas Martins",
    location: "São Paulo, Brazil",
    amount: 31200.45,
    timestamp: new Date(),
  },
  {
    id: "6",
    type: "investment", 
    name: "Priya Patel",
    location: "Mumbai, India",
    amount: 15600.90,
    timestamp: new Date(),
  },
  {
    id: "7",
    type: "withdrawal",
    name: "Michael Nguyen",
    location: "Sydney, Australia",
    amount: 67500.30,
    timestamp: new Date(),
  },
  {
    id: "8",
    type: "investment",
    name: "Emily Davis",
    location: "Toronto, Canada", 
    amount: 38900.75,
    timestamp: new Date(),
  },
  {
    id: "9",
    type: "withdrawal",
    name: "Daniel Kim",
    location: "Seoul, South Korea",
    amount: 29800.60,
    timestamp: new Date(),
  },
  {
    id: "10",
    type: "investment",
    name: "Sofia Lopez",
    location: "Madrid, Spain",
    amount: 21450.85,
    timestamp: new Date(),
  },
  {
    id: "11",
    type: "withdrawal",
    name: "Tom Anderson",
    location: "Berlin, Germany",
    amount: 45600.20,
    timestamp: new Date(),
  },
  {
    id: "12",
    type: "investment",
    name: "Nina Roberts",
    location: "Paris, France",
    amount: 33750.40,
    timestamp: new Date(),
  },
  {
    id: "13",
    type: "withdrawal",
    name: "Chen Wei",
    location: "Shanghai, China",
    amount: 52800.15,
    timestamp: new Date(),
  },
  {
    id: "14",
    type: "investment",
    name: "Marcus Johnson",
    location: "Los Angeles, USA",
    amount: 41250.60,
    timestamp: new Date(),
  },
  {
    id: "15",
    type: "withdrawal",
    name: "Isabella Rossi",
    location: "Rome, Italy",
    amount: 28900.35,
    timestamp: new Date(),
  },
  {
    id: "16",
    type: "investment",
    name: "Ahmed Hassan",
    location: "Cairo, Egypt",
    amount: 19500.80,
    timestamp: new Date(),
  },
  {
    id: "17",
    type: "withdrawal",
    name: "Emma Wilson",
    location: "Manchester, UK",
    amount: 36750.45,
    timestamp: new Date(),
  },
  {
    id: "18",
    type: "investment",
    name: "Yuki Tanaka",
    location: "Tokyo, Japan",
    amount: 44500.25,
    timestamp: new Date(),
  },
  {
    id: "19",
    type: "withdrawal",
    name: "Carlos Rodriguez",
    location: "Mexico City, Mexico",
    amount: 22300.70,
    timestamp: new Date(),
  },
  {
    id: "20",
    type: "investment",
    name: "Lisa Anderson",
    location: "Stockholm, Sweden",
    amount: 31800.90,
    timestamp: new Date(),
  },
  {
    id: "21",
    type: "withdrawal",
    name: "Rajesh Kumar",
    location: "Delhi, India",
    amount: 15400.50,
    timestamp: new Date(),
  },
  {
    id: "22",
    type: "investment",
    name: "Olivia Brown",
    location: "Melbourne, Australia",
    amount: 47200.30,
    timestamp: new Date(),
  },
  {
    id: "23",
    type: "withdrawal",
    name: "Mohammed Al-Rashid",
    location: "Riyadh, Saudi Arabia",
    amount: 61200.85,
    timestamp: new Date(),
  },
  {
    id: "24",
    type: "investment",
    name: "Sophie Laurent",
    location: "Lyon, France",
    amount: 27600.40,
    timestamp: new Date(),
  },
  {
    id: "25",
    type: "withdrawal",
    name: "David Lee",
    location: "Singapore",
    amount: 38900.20,
    timestamp: new Date(),
  },
  {
    id: "26",
    type: "investment",
    name: "Maria Garcia",
    location: "Barcelona, Spain",
    amount: 33400.65,
    timestamp: new Date(),
  },
  {
    id: "27",
    type: "withdrawal",
    name: "Alexander Petrov",
    location: "Moscow, Russia",
    amount: 42800.10,
    timestamp: new Date(),
  },
  {
    id: "28",
    type: "investment",
    name: "Jennifer White",
    location: "Vancouver, Canada",
    amount: 29100.75,
    timestamp: new Date(),
  },
  {
    id: "29",
    type: "withdrawal",
    name: "Hassan Ali",
    location: "Istanbul, Turkey",
    amount: 35600.30,
    timestamp: new Date(),
  },
  {
    id: "30",
    type: "investment",
    name: "Charlotte Taylor",
    location: "Amsterdam, Netherlands",
    amount: 40100.55,
    timestamp: new Date(),
  }
];

export default userActions;
